### admin@admin.com
GET http://localhost:8080/api/login
Authorization: Basic YWRtaW5AYWRtaW4uY29tOmFkbWlu
###

### user@user.com
GET http://localhost:8080/api/login
Authorization: Basic dXNlckB1c2VyLmNvbTp1c2Vy
###

GET http://localhost:8080/api/hospital
Authorization: Bearer
###

POST http://localhost:8080/api/hospital
Authorization: Bearer
Content-Type: application/json

{
  "nome": "hosp2",
  "local": "ccc"
}
###

GET http://localhost:8080/api/check/login
Authorization: Bearer
###

POST http://localhost:8080/api/cotacao
Content-Type: application/json

{
  "profissao": "Empresário Individual"
}
###
