insert into Entidade (id, nome) values (1, 'ABECA');
insert into Entidade (id, nome) values (2, 'ABESP DF');
insert into Entidade (id, nome) values (3, 'ABRABDIR');
insert into Entidade (id, nome) values (4, 'ABRACEM');
insert into Entidade (id, nome) values (5, 'ACRESP');
insert into Entidade (id, nome) values (6, 'ADPF');
insert into Entidade (id, nome) values (7, 'AESP/DF');
insert into Entidade (id, nome) values (8, 'AFB');
insert into Entidade (id, nome) values (9, 'AJUFE');
insert into Entidade (id, nome) values (10, 'AMAGIS');
insert into Entidade (id, nome) values (11, 'AMAI');
insert into Entidade (id, nome) values (12, 'AMB');
insert into Entidade (id, nome) values (13, 'AMBr');
insert into Entidade (id, nome) values (14, 'AMN');
insert into Entidade (id, nome) values (15, 'ANADEF');
insert into Entidade (id, nome) values (16, 'ANAMATRA');
insert into Entidade (id, nome) values (17, 'ANATO');
insert into Entidade (id, nome) values (18, 'ASCOM');
insert into Entidade (id, nome) values (19, 'ASMPF');
insert into Entidade (id, nome) values (20, 'CAA-DF');
insert into Entidade (id, nome) values (21, 'CNPL');
insert into Entidade (id, nome) values (22, 'CORECON-DF');
insert into Entidade (id, nome) values (23, 'CRA-DF');
insert into Entidade (id, nome) values (24, 'CRBio-4');
insert into Entidade (id, nome) values (25, 'CREF7');
insert into Entidade (id, nome) values (26, 'CRF-DF');
insert into Entidade (id, nome) values (27, 'CRO-DF');
insert into Entidade (id, nome) values (28, 'CRP-01');
insert into Entidade (id, nome) values (29, 'FEBRAD');
insert into Entidade (id, nome) values (30, 'FECOMÉRCIO');
insert into Entidade (id, nome) values (31, 'FECOMÉRCIO - DF');
insert into Entidade (id, nome) values (32, 'FEIFAR');
insert into Entidade (id, nome) values (33, 'FENAMEV');
insert into Entidade (id, nome) values (34, 'FETRACOM');
insert into Entidade (id, nome) values (35, 'FETRATUH');
insert into Entidade (id, nome) values (36, 'FINAFITO');
insert into Entidade (id, nome) values (37, 'FNN');
insert into Entidade (id, nome) values (38, 'FNO');
insert into Entidade (id, nome) values (39, 'MÚTUA');
insert into Entidade (id, nome) values (40, 'SASPB');
insert into Entidade (id, nome) values (41, 'SINDICOM-DF');
insert into Entidade (id, nome) values (42, 'SINDICONTA-DF');
insert into Entidade (id, nome) values (43, 'SINDMÉDICO - DF');
insert into Entidade (id, nome) values (44, 'SINDPSICOP - BR');
insert into Entidade (id, nome) values (45, 'SINPROEP - DF');
insert into Entidade (id, nome) values (46, 'SINPROEP');
insert into Entidade (id, nome) values (47, 'UBES');
insert into Entidade (id, nome) values (48, 'UNE');
