insert into Profissao (id, nome) values (1, 'Autônomo');
insert into Profissao (id, nome) values (2, 'Empresário');
insert into Profissao (id, nome) values (3, 'Empresário Individual');
insert into Profissao (id, nome) values (4, 'Comerciário');
insert into Profissao (id, nome) values (5, 'Empregados do Conselho de Adm');
insert into Profissao (id, nome) values (6, 'Servidor Público Distrital');
insert into Profissao (id, nome) values (7, 'Servidor Público Federal');
insert into Profissao (id, nome) values (8, 'Delegado da Polícia Federal');
insert into Profissao (id, nome) values (9, 'Defensor Público');
insert into Profissao (id, nome) values (10, 'Juiz Federal');
insert into Profissao (id, nome) values (11, 'Servidor da Receita');
insert into Profissao (id, nome) values (12, 'Servidor do Detran');
insert into Profissao (id, nome) values (13, 'Servidor do Ministério Público Federal');
insert into Profissao (id, nome) values (14, 'Magistrado');
insert into Profissao (id, nome) values (15, 'Estudante Ed Infantil');
insert into Profissao (id, nome) values (16, 'Estudante Secundarista');
insert into Profissao (id, nome) values (17, 'Estudante de Faculdade');
insert into Profissao (id, nome) values (18, 'Estudante de Direito');
insert into Profissao (id, nome) values (19, 'Estudante de Contabilidade 7º  em diante');
insert into Profissao (id, nome) values (20, 'Profissional Liberal');
insert into Profissao (id, nome) values (21, 'Administrador com CRA');
insert into Profissao (id, nome) values (22, 'Administrador sem CRA');
insert into Profissao (id, nome) values (23, 'Advogado C/ OAB');
insert into Profissao (id, nome) values (24, 'Advogado s/ OAB');
insert into Profissao (id, nome) values (25, 'Estagiário Advogado');
insert into Profissao (id, nome) values (26, 'Agronomo');
insert into Profissao (id, nome) values (27, 'Arquiteto');
insert into Profissao (id, nome) values (28, 'Biologo');
insert into Profissao (id, nome) values (29, 'Contador');
insert into Profissao (id, nome) values (30, 'Dentista');
insert into Profissao (id, nome) values (31, 'Economista');
insert into Profissao (id, nome) values (32, 'Educação Física');
insert into Profissao (id, nome) values (33, 'Engenheiro');
insert into Profissao (id, nome) values (34, 'Farmacêutico');
insert into Profissao (id, nome) values (35, 'Fisioterapeuta');
insert into Profissao (id, nome) values (36, 'Médico');
insert into Profissao (id, nome) values (37, 'Marinheiro');
insert into Profissao (id, nome) values (38, 'Nutricionista');
insert into Profissao (id, nome) values (39, 'Piloto de Aviação');
insert into Profissao (id, nome) values (40, 'Psicólogo');
insert into Profissao (id, nome) values (41, 'Psicopedagogo');
insert into Profissao (id, nome) values (42, 'Professor Particular');
insert into Profissao (id, nome) values (43, 'Técnico em Odontologia');
insert into Profissao (id, nome) values (44, 'Técnico Industrial');
insert into Profissao (id, nome) values (45, 'Tradutor');
insert into Profissao (id, nome) values (46, 'Veterinário');
