insert into entidade_profissao (Entidade_id, profissoes_id) values (3, 2);
insert into entidade_profissao (Entidade_id, profissoes_id) values (4, 3);
insert into entidade_profissao (Entidade_id, profissoes_id) values (6, 2);
insert into entidade_profissao (Entidade_id, profissoes_id) values (7, 2);
insert into entidade_profissao (Entidade_id, profissoes_id) values (2, 2);
insert into entidade_profissao (Entidade_id, profissoes_id) values (1, 3);
insert into entidade_profissao (Entidade_id, profissoes_id) values (1, 6);
insert into entidade_profissao (Entidade_id, profissoes_id) values (5, 1);
insert into entidade_profissao (Entidade_id, profissoes_id) values (5, 6);
